pagecall/pagecall-android-sdk

pagecall/src/main/assets/js/PagecallNative.js
pagecall/src/main/assets/js/src/PagecallNative.ts
pagecall/src/main/java/com/pagecall/AudioRecordManager.java
pagecall/src/main/java/com/pagecall/NativeBridge.java
pagecall/src/main/java/com/pagecall/NativeBridgeAction.java
pagecall/src/main/java/com/pagecall/PagecallWebView.java
sample/src/main/java/com/pagecall/sample/MainActivity.java
sample/src/main/res/layout/activity_main.xml

https://github.com/pagecall/pagecall-ios-sdk/pull/15 이 PR과 동일한 기능을 추가합니다.
이 과정에서 NativeBridgeAction.LOADED 를 새로 생성했습니다.

feat: implement sendMessage, listenMessage

---

pagecall/build.gradle
pagecall/src/main/java/com/pagecall/PagecallWebView.java
sample/src/main/java/com/pagecall/sample/MainActivity.java

- PagecallWebView가 pagecallUrls를 받을 수 있습니다.
- defaultPagecallUrls에 "demo.pagecall" 을 추가합니다.
- SDK version을 0.0.3으로 올립니다.

feat: PagecallWebView receive pagecallUrls (Update SDK to 0.0.3)

---

pagecall/src/main/java/com/pagecall/NativeBridge.java
pagecall/src/main/java/com/pagecall/WebViewEmitter.java

chore: logs for debugging

---

README.md
pagecall/build.gradle
pagecall/src/main/java/com/pagecall/AudioRecordManager.java
pagecall/src/main/java/com/pagecall/PagecallWebView.java

Adjust volume sensitivity

---

pagecall/build.gradle

pagecall 모듈에서는 material이 불필요하여 삭제합니다.

material을 삭제합니다.

---

pagecall/build.gradle
pagecall/src/main/java/com/pagecall/NativeBridge.java

- AudioManager의 모드를 `MODE_IN_COMMUNICATION`로 설정합니다.
- 버전을 0.0.16으로 올립니다.
Ref: https://developer.android.com/reference/android/media/AudioManager?authuser=1#MODE_IN_COMMUNICATION
테스트 항목
- 샘플앱에서 WebView를 닫았다가 열어도 볼륨이 유지되는가
- 이어폰을 꽂았다 빼도 볼륨이 유지되는가

마이크 수음 볼륨이 너무 낮은 이슈를 픽스합니다.

---

README.md
pagecall/build.gradle
pagecall/src/main/java/com/pagecall/PagecallWebView.java
sample/build.gradle
sample/pagecall-webview/build.gradle

https://pagecall.slack.com/archives/C04HLEP4D3L/p1689152185516979

minSdk를 24 -> 23으로 낮춥니다.

---

README.md
pagecall/build.gradle
pagecall/src/main/java/com/pagecall/NativeBridge.java
pagecall/src/main/java/com/pagecall/PagecallWebView.java

https://pagecall.slack.com/archives/C04HLEP4D3L/p1690878085102649

Android SDK 24 미만에서 크래시가 나는 이슈를 픽스합니다.

---

README.md
pagecall/build.gradle
pagecall/src/main/java/com/pagecall/NativeBridge.java
pagecall/src/main/java/com/pagecall/PagecallWebView.java
sample/src/main/java/com/pagecall/sample/MainActivity.java

https://pagecall.slack.com/archives/C04HLEP4D3L/p1690887397443329?thread_ts=1690878085.102649&cid=C04HLEP4D3L

android sdk 24 아래 버전에서 페이지 로드가 되지 않는 이슈를 픽스합니다.

---

README.md
pagecall/build.gradle
pagecall/src/main/java/com/pagecall/PagecallWebView.java
sample/src/main/java/com/pagecall/sample/MainActivity.java

https://www.notion.so/pplink/SDK-b1303d926bfc4e3fb14addac39ed6ee9?pvs=4

WebView.loadUrl()을 직접 쓰는 것을 지양합니다.

---

pagecall/src/main/java/com/pagecall/PagecallWebView.java

setMediaPlaybackRequiresUserGesture false to avoid audio issues

fix: setMediaPlaybackRequiresUserGesture false

---

pagecall/src/main/java/com/pagecall/MediaInfraController.java
pagecall/src/main/java/com/pagecall/PagecallWebView.java

- Ensure that MediaInfraController.dispose() occurs only on the main thread to prevent crashes due to race conditions

fix: concurrency control in MediaInfraController.dispose()

---

sample/src/main/java/com/pagecall/sample/PagecallFragment.java
sample/src/main/res/layout/fragment_pagecall.xml

- adjust PagecallFragment layout
- navigate back on terminate

feat: adjust PagecallFragment layout, navigate back on terminate

---

pagecall/src/main/java/com/pagecall/MediaInfraController.java
pagecall/src/main/java/com/pagecall/NativeBridge.java
pagecall/src/main/java/com/pagecall/NativeBridgeAction.java

handle "getMediaStats" request from web app

feat: handle "getMediaStats" request from web app

---

README.md
pagecall/build.gradle
pagecall/src/main/java/com/pagecall/NativeBridgeAction.java
pagecall/src/main/java/com/pagecall/PagecallWebView.java
sample/src/main/java/com/pagecall/sample/PagecallFragment.java

- Support onEvent(event) handler

feat: onEvent handler

---

pagecall/build.gradle
pagecall/src/main/java/com/pagecall/ChimeAudioVideoObserver.java
pagecall/src/main/java/com/pagecall/ChimeController.java
pagecall/src/main/java/com/pagecall/ChimeDeviceChangeObserver.java
pagecall/src/main/java/com/pagecall/ChimeMetricsObserver.java
pagecall/src/main/java/com/pagecall/ChimeRealtimeObserver.java
pagecall/src/main/java/com/pagecall/MediaController.java
pagecall/src/main/java/com/pagecall/MediaInfraController.java
pagecall/src/main/java/com/pagecall/NativeBridge.java
pagecall/src/main/java/com/pagecall/WebViewEmitter.java
sample/build.gradle

feat: support chime sdk

---

pagecall/src/main/java/com/pagecall/PagecallWebView.java

- Support `setValue` which was introduced in https://github.com/pagecall/react-native-pagecall/pull/26

Support `setValue`

---

pagecall/build.gradle
pagecall/src/main/java/com/pagecall/PagecallWebView.java
sample/src/main/java/com/pagecall/sample/PagecallFragment.java

- Handles renderer process error
- Logs navigation to detect unexpected ones

Log possible errors (0.0.44)

---

README.md
pagecall/build.gradle
pagecall/src/main/java/com/pagecall/PagecallWebView.java

Fixes an issue introduced in #60 where wired earphones were not being used, and the speakerphone was used instead.

Wired headphones (0.0.45)

---

pagecall/src/main/java/com/pagecall/PagecallWebView.java
sample/src/main/java/com/pagecall/sample/PagecallFragment.java

* Added the onLoadStateChange method to the Listener interface.

feat: add onLoadStateChange method to Listener interface

---

README.md
pagecall/build.gradle
pagecall/src/main/java/com/pagecall/PagecallWebView.java

release: 0.0.47

---

pagecall/src/main/java/com/pagecall/PagecallWebView.java
sample/src/main/java/com/pagecall/sample/PagecallFragment.java

Detect URL changes within the webview.
This is intended for special cases where a URL other than app.pagecall.com needs to be rendered.

feat: onWillNavigate
